apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-updater-job
spec:
  schedule: "*/10 * * * *"  # Every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: auto-updater
            image: wishula/auto-updater:latest
            env:
            - name: PROMETHEUS_URL
              value: "http://192.248.41.95:9090"
          restartPolicy: Never
