apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-client
  template:
    metadata:
      labels:
        app: sentiment-client
    spec:
      containers:
      - name: client
        image: wishula/sentiment-client:latest
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
