apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-client
  template:
    metadata:
      labels:
        app: sentiment-client
    spec:
      containers:
      - name: sentiment-client
        image: wishula/sentiment-client:latest
