apiVersion: batch/v1
kind: CronJob
metadata:
  name: reduce-mem-s2-cronjob
  namespace: default
spec:
  schedule: "0 */3 * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: reduce-mem
              image: bitnami/kubectl:latest
              command: ["/bin/bash", "/scripts/reduce_mem_s2.sh"]
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
          restartPolicy: OnFailure
          serviceAccountName: default
          volumes:
            - name: script-volume
              configMap:
                name: reduce-mem-s2-script
                defaultMode: 0755
