apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2-deployment
  namespace: default
  labels:
    app: service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3002"
    spec:
      containers:
        - name: service-2-container
          image: wishula/service-2-image:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-2-service
  namespace: default
  labels:
    app: service-2
spec:
  selector:
    app: service-2
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer
