apiVersion: v1
kind: ConfigMap
metadata:
  name: prime-load-generator-script
  namespace: default
data:
  generate_load.sh: |
    #!/bin/bash

    SERVICE_URL="http://service-1-service:3001/isPrime"


    DURATION=600  # 10 minutes in seconds

    # Function to generate random primes workload
    generate_load() {
      end=$((SECONDS + DURATION))
      echo "Starting load generation for 10 minutes..."
      while [ $SECONDS -lt $end ]; do
        # Generate a random number between 10,000 and 20,000
        NUM=$(( RANDOM % 10000 + 10000 ))
        # Call the prime check endpoint
        curl -s "${SERVICE_URL}?number=${NUM}" > /dev/null
        sleep 0.2  # 5 requests per second approx
      done
      echo "Load generation period finished."
    }

    # Run load twice, with different number ranges (simulate workload variation)
    echo "Generating first load phase..."
    generate_load

    echo "Waiting 10 seconds before second load phase..."
    sleep 10

    echo "Generating second load phase..."
    # Adjust random number range to generate different load
    generate_load() {
      end=$((SECONDS + DURATION))
      echo "Starting second load generation for 10 minutes..."
      while [ $SECONDS -lt $end ]; do
        NUM=$(( RANDOM % 10000 + 20000 ))
        curl -s "${SERVICE_URL}?number=${NUM}" > /dev/null
        sleep 0.2
      done
      echo "Second load generation finished."
    }
    generate_load

    echo "Load generation complete."
