apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-controller-script
  namespace: default
data:
  load_wave.sh: |
    #!/bin/bash

    STATE_FILE="/data/step_counter.txt"
    MAX_STEP=6  # 0 to 6 increase, 7 to 12 decrease

    mkdir -p /data

    # Initialize step if not exists
    if [ ! -f "$STATE_FILE" ]; then
      echo "0" > "$STATE_FILE"
    fi

    STEP=$(cat "$STATE_FILE")

    # Calculate load level
    if [ "$STEP" -le "$MAX_STEP" ]; then
      LOAD=$STEP
    else
      LOAD=$((2 * MAX_STEP - STEP))
    fi

    echo "Current step: $STEP, Load level: $LOAD"

    # Simulate load (e.g., CPU-bound using stress-ng)
    DURATION=$((LOAD + 1))  # ensure minimum duration
    echo "Running stress for $DURATION seconds"
    stress-ng --cpu 1 --timeout ${DURATION}s --metrics-brief

    # Increment step, wrap after 2*MAX_STEP + 1
    STEP=$(( (STEP + 1) % (2 * MAX_STEP + 1) ))
    echo "$STEP" > "$STATE_FILE"
