apiVersion: v1
kind: ConfigMap
metadata:
  name: prime-load-generator-2-script
  namespace: default
data:
  generate_load_2.sh: |
    #!/bin/bash

    # Install curl if missing
    if ! command -v curl &> /dev/null; then
      echo "curl not found, installing..."
      apt-get update && apt-get install -y curl
    fi

    if ! command -v bc &> /dev/null; then
      echo "bc not found, installing..."
      apt-get update && apt-get install -y bc
    fi


    SERVICE_URL="http://service-2-service:3002/echoNumber"
    DURATION=600  # 10 minutes

    # Pick a random requests per second (RPS) between 1 and 10
    RPS=$(( RANDOM % 100 + 1 ))
    SLEEP_TIME=$(echo "scale=4; 1 / $RPS" | bc)

    # Pick a random number range for the requests
    START_NUM=$(( RANDOM % 20000 + 10000 ))
    END_NUM=$(( START_NUM + 10000 ))

    echo "Generating load at $RPS requests/second for 10 minutes..."
    echo "Number range: $START_NUM to $END_NUM"

    end=$((SECONDS + DURATION))
    while [ $SECONDS -lt $end ]; do
      NUM=$(( RANDOM % (END_NUM - START_NUM) + START_NUM ))
      curl -s "${SERVICE_URL}?number=${NUM}" > /dev/null
      sleep $SLEEP_TIME
    done

    echo "Load generation complete."
