apiVersion: batch/v1
kind: CronJob
metadata:
  name: prime-load-generator
  namespace: default
spec:
  schedule: "*/20 * * * *"  # every 20 minutes (to run two load phases)
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: load-generator
            image: bash:5.1   # lightweight curl image
            command: ["/bin/bash", "/scripts/generate_load.sh"]
            volumeMounts:
              - name: script-volume
                mountPath: /scripts
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: prime-load-generator-script
                defaultMode: 0755