apiVersion: batch/v1
kind: CronJob
metadata:
  name: prime-load-cronjob
  namespace: default
spec:
  schedule: "0 */3 * * *" # every 3 hours
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 6
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: prime-load
              image: curlimages/curl:latest
              command: ["/bin/sh", "/scripts/load_generator.sh"]
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: prime-load-script
                defaultMode: 0755
