apiVersion: v1
kind: Service
metadata:
  name: service-1-service
  namespace: default
  labels:
    app: service-1
spec:
  selector:
    app: service-1
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: LoadBalancer
=======
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1-deployment
  namespace: default
  labels:
    app: service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "3005"
    spec:
      containers:
        - name: service-1-container
          image: service-1-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3005
          resources:
            requests:
              cpu: "100m"
              memory: "20Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-1-service
  namespace: default
  labels:
    app: service-1
spec:
  selector:
    app: hash-gen
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: LoadBalancer

