# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: "AI Dirven Latency Constrained Resource Management In Kubernetes"
remote_theme: cepdnaclk/eYY-project-theme
description: "Focuses on latency-aware resource optimization for Kubernetes"
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
