# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: "Dynamic Multi Dimensional Resource Orchestration in Kubernetes"
remote_theme: cepdnaclk/e19-Dynamic-Multi-Dimensional-Resource-Orchestration-in-Kubernetes
description: "focuses on latency-aware resource optimization for Kubernetes"
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
