apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoip-client1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoip-client1
  template:
    metadata:
      labels:
        app: geoip-client1
    spec:
      containers:
      - name: geoip-client1
        image: wishula/ip-geo-client1:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
