apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoip-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoip-client
  template:
    metadata:
      labels:
        app: geoip-client
    spec:
      containers:
      - name: geoip-client
        image: wishula/ip-geo-client:latest
