apiVersion: v1
kind: Service
metadata:
  name: ip-geo-service
spec:
  selector:
    app: ip-geo
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: metrics
      port: 8001
      targetPort: 8001
