apiVersion: v1
kind: Service
metadata:
  name: ip-geo-service
spec:
  type: NodePort
  selector:
    app: ip-geo
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080  # Access via <NodeIP>:30080
    - name: metrics
      port: 8001
      targetPort: 8001
      nodePort: 30081  # Access via <NodeIP>:30081
