apiVersion: apps/v1
kind: Deployment
metadata:
  name: rand-pw-gen-deployment
  namespace: default
  labels:
    app: rand-pw-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rand-pw-gen
  template:
    metadata:
      labels:
        app: rand-pw-gen
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "3003"
    spec:
      containers:
        - name: rand-pw-gen-container
          image: rand-pw-gen-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: rand-pw-gen-service
  namespace: default
  labels:
    app: rand-pw-gen
spec:
  selector:
    app: rand-pw-gen
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: LoadBalancer
