name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Java Service
      run: |
        cd java-service
        ./gradlew build  # or 'mvn clean install' depending on your project

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Go Service
      run: |
        cd go-service
        go build -o app

    - name: Deploy to Server
      run: |
        cd /var/www/myapp
        git pull origin main
        ./restart.sh  # Custom script to restart your services
